import Head from "next/head";
import { Inter } from "@next/font/google";
import Layout1 from "@/components/layouts/Layout1";
import Hero from "@/components/sections/Hero";
import HomeIntro from "@/components/sections/HomeIntro";
import HomeSteps from "@/components/sections/HomeSteps";
import HomeReviews from "@/components/sections/HomeReviews";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Oroxat</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <Layout1>
                <section>
                    <Hero />
                </section>

                {/* introduction */}
                <section>
                    <HomeIntro />
                </section>
                <section>
                    <HomeSteps />
                </section>
                <section>
                    <HomeReviews />
                </section>
            </Layout1>
        </>
    );
}
